import { app, BrowserWindow, ipcMain } from 'electron';
import { initDatabase, closeDatabase, getDatabase } from './database';
// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

const createWindow = (): void => {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    height: 600,
    width: 800,
    titleBarStyle: 'hidden',
    titleBarOverlay: process.platform === 'win32' ? {
      color: '#212529',
      symbolColor: '#ffffff',
      height: 44
    } : false,
    trafficLightPosition: { x: 15, y: 15 }, // Adjusted for 44px height
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  // Open the DevTools.
  // mainWindow.webContents.openDevTools();
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', async () => {
  try {
    await initDatabase();
    console.log('Database initialized successfully');
    
    // Example: verify migrations worked
    const db = getDatabase();
    const tables = await db.all("SELECT name FROM sqlite_master WHERE type='table'");
    console.log('Tables in database:', tables.map(t => t.name).join(', '));
  } catch (error) {
    console.error('Failed to initialize database:', error);
  }
  createWindow();
});

// Setup IPC handlers for DB
ipcMain.handle('db-query', async (event, sql, params) => {
  const db = getDatabase();
  return await db.all(sql, params);
});

ipcMain.handle('db-run', async (event, sql, params) => {
  const db = getDatabase();
  return await db.run(sql, params);
});

ipcMain.handle('create-project', async (event, project: { title: string; prefix: string; startDate?: string; dueDate?: string; ownerId?: number }) => {
  const db = getDatabase();
  const result = await db.run(
    'INSERT INTO Project (Title, Prefix, StartDate, DueDate, OwnerId) VALUES (?, ?, ?, ?, ?)',
    [project.title, project.prefix, project.startDate || null, project.dueDate || null, project.ownerId || null]
  );
  return result;
});

ipcMain.handle('get-project', async (event, id: number) => {
  const db = getDatabase();
  return await db.get('SELECT * FROM Project WHERE Id = ?', [id]);
});

ipcMain.handle('update-project', async (event, project: { id: number; title: string; prefix: string; startDate?: string; dueDate?: string; ownerId?: number }) => {
  const db = getDatabase();
  const result = await db.run(
    'UPDATE Project SET Title = ?, Prefix = ?, StartDate = ?, DueDate = ?, OwnerId = ? WHERE Id = ?',
    [project.title, project.prefix, project.startDate || null, project.dueDate || null, project.ownerId || null, project.id]
  );
  return result;
});

// Person IPC Handlers
ipcMain.handle('get-people', async () => {
  const db = getDatabase();
  return await db.all('SELECT * FROM Person ORDER BY Name ASC');
});

ipcMain.handle('create-person', async (event, person: { name: string; email: string; color?: string }) => {
  const db = getDatabase();
  return await db.run(
    'INSERT INTO Person (Name, Email, Color) VALUES (?, ?, ?)',
    [person.name, person.email, person.color || null]
  );
});

ipcMain.handle('update-person', async (event, person: { id: number; name: string; email: string; color?: string }) => {
  const db = getDatabase();
  return await db.run(
    'UPDATE Person SET Name = ?, Email = ?, Color = ? WHERE Id = ?',
    [person.name, person.email, person.color || null, person.id]
  );
});

ipcMain.handle('delete-person', async (event, id: number) => {
  const db = getDatabase();
  return await db.run('DELETE FROM Person WHERE Id = ?', [id]);
});

// Status IPC Handlers
ipcMain.handle('get-statuses', async () => {
  const db = getDatabase();
  return await db.all('SELECT * FROM Status ORDER BY Id ASC');
});

ipcMain.handle('create-status', async (event, status: { label: string; isNew: boolean; isComplete: boolean }) => {
  const db = getDatabase();
  return await db.run(
    'INSERT INTO Status (Label, IsNew, IsComplete) VALUES (?, ?, ?)',
    [status.label, status.isNew ? 1 : 0, status.isComplete ? 1 : 0]
  );
});

ipcMain.handle('update-status', async (event, status: { id: number; label: string; isNew: boolean; isComplete: boolean }) => {
  const db = getDatabase();
  return await db.run(
    'UPDATE Status SET Label = ?, IsNew = ?, IsComplete = ? WHERE Id = ?',
    [status.label, status.isNew ? 1 : 0, status.isComplete ? 1 : 0, status.id]
  );
});

ipcMain.handle('delete-status', async (event, id: number) => {
  const db = getDatabase();
  return await db.run('DELETE FROM Status WHERE Id = ?', [id]);
});

// Task IPC Handlers
ipcMain.handle('get-task', async (event, id: number) => {
  const db = getDatabase();
  const task = await db.get(`
    SELECT t.*, p.Name as AssigneeName, s.Label as StatusLabel, s.IsComplete, pt.Title as ParentTitle
    FROM Task t
    LEFT JOIN Person p ON t.AssigneeId = p.Id
    LEFT JOIN Status s ON t.StatusId = s.Id
    LEFT JOIN Task pt ON t.ParentId = pt.Id
    WHERE t.Id = ?
  `, [id]);

  if (!task) return null;

  const prerequisites = await db.all(`
    SELECT tp.*, t.Title as PrerequisiteTaskTitle, s.IsComplete as PrerequisiteIsComplete
    FROM TaskPrerequisite tp
    JOIN Task t ON tp.PrerequisiteTaskId = t.Id
    LEFT JOIN Status s ON t.StatusId = s.Id
    WHERE tp.TaskId = ?
  `, [id]);

  const dependedOnBy = await db.all(`
    SELECT tp.*, t.Title as DependentTaskTitle, s.IsComplete as DependentIsComplete
    FROM TaskPrerequisite tp
    JOIN Task t ON tp.TaskId = t.Id
    LEFT JOIN Status s ON t.StatusId = s.Id
    WHERE tp.PrerequisiteTaskId = ?
  `, [id]);

  return { task, prerequisites, dependedOnBy };
});

ipcMain.handle('get-project-tasks', async (event, projectId: number) => {
  const db = getDatabase();
  const tasks = await db.all(`
    SELECT t.*, p.Name as AssigneeName, s.Label as StatusLabel, s.IsComplete, pt.Title as ParentTitle
    FROM Task t
    LEFT JOIN Person p ON t.AssigneeId = p.Id
    LEFT JOIN Status s ON t.StatusId = s.Id
    LEFT JOIN Task pt ON t.ParentId = pt.Id
    WHERE t.ProjectId = ?
    ORDER BY t.SortOrder ASC, t.DisplayId ASC
  `, [projectId]);

  // Get prerequisites where either the task or the prerequisite is in the project
  // This ensures we have both what tasks in the project depend on, 
  // and what depends on tasks in the project.
  const prerequisites = await db.all(`
    SELECT tp.*, 
           pt.Title as PrerequisiteTaskTitle, 
           ps.IsComplete as PrerequisiteIsComplete,
           dt.Title as DependentTaskTitle,
           ds.IsComplete as DependentIsComplete
    FROM TaskPrerequisite tp
    JOIN Task pt ON tp.PrerequisiteTaskId = pt.Id
    JOIN Task dt ON tp.TaskId = dt.Id
    LEFT JOIN Status ps ON pt.StatusId = ps.Id
    LEFT JOIN Status ds ON dt.StatusId = ds.Id
    WHERE pt.ProjectId = ? OR dt.ProjectId = ?
  `, [projectId, projectId]);

  return { tasks, prerequisites };
});

ipcMain.handle('create-task', async (event, task: { 
  displayId: number;
  title: string; 
  projectId: number; 
  sortOrder: number;
  description?: string; 
  assigneeId?: number; 
  statusId?: number 
}) => {
  const db = getDatabase();
  return await db.run(
    'INSERT INTO Task (DisplayId, Title, ProjectId, SortOrder, Description, AssigneeId, StatusId) VALUES (?, ?, ?, ?, ?, ?, ?)',
    [
      task.displayId,
      task.title, 
      task.projectId, 
      task.sortOrder,
      task.description || null, 
      task.assigneeId || null, 
      task.statusId || null
    ]
  );
});

ipcMain.handle('add-prerequisite', async (event, { taskId, prerequisiteTaskId, type }) => {
  const db = getDatabase();
  return await db.run(
    'INSERT INTO TaskPrerequisite (TaskId, PrerequisiteTaskId, Type) VALUES (?, ?, ?)',
    [taskId, prerequisiteTaskId, type]
  );
});

ipcMain.handle('update-prerequisite', async (event, { taskId, prerequisiteTaskId, type }) => {
  const db = getDatabase();
  return await db.run(
    'UPDATE TaskPrerequisite SET Type = ? WHERE TaskId = ? AND PrerequisiteTaskId = ?',
    [type, taskId, prerequisiteTaskId]
  );
});

ipcMain.handle('delete-prerequisite', async (event, { taskId, prerequisiteTaskId }) => {
  const db = getDatabase();
  return await db.run(
    'DELETE FROM TaskPrerequisite WHERE TaskId = ? AND PrerequisiteTaskId = ?',
    [taskId, prerequisiteTaskId]
  );
});

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', async () => {
  await closeDatabase();
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('will-quit', async () => {
  await closeDatabase();
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});
