import { app, BrowserWindow, ipcMain, shell } from 'electron';
import * as azdev from 'azure-devops-node-api';
import * as WITInterfaces from 'azure-devops-node-api/interfaces/WorkItemTrackingInterfaces';
import { initDatabase, closeDatabase, getDatabase } from './database';
// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

const createWindow = (): void => {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    height: 600,
    width: 800,
    titleBarStyle: 'hidden',
    titleBarOverlay: process.platform === 'win32' ? {
      color: '#212529',
      symbolColor: '#ffffff',
      height: 44
    } : false,
    trafficLightPosition: { x: 15, y: 15 }, // Adjusted for 44px height
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  // Open the DevTools.
  // mainWindow.webContents.openDevTools();
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', async () => {
  try {
    await initDatabase();
    console.log('Database initialized successfully');
    
    // Example: verify migrations worked
    const db = getDatabase();
    const tables = await db.all("SELECT name FROM sqlite_master WHERE type='table'");
    console.log('Tables in database:', tables.map(t => t.name).join(', '));
  } catch (error) {
    console.error('Failed to initialize database:', error);
  }
  createWindow();
});

// Setup IPC handlers for DB
ipcMain.handle('db-query', async (event, sql, params) => {
  const db = getDatabase();
  return await db.all(sql, params);
});

ipcMain.handle('db-run', async (event, sql, params) => {
  const db = getDatabase();
  return await db.run(sql, params);
});

ipcMain.handle('create-project', async (event, project: { title: string; prefix: string; startDate?: string; dueDate?: string; ownerId?: number; taskSourceId?: number }) => {
  const db = getDatabase();
  const result = await db.run(
    'INSERT INTO Project (Title, Prefix, StartDate, DueDate, OwnerId, TaskSourceId) VALUES (?, ?, ?, ?, ?, ?)',
    [project.title, project.prefix, project.startDate || null, project.dueDate || null, project.ownerId || null, project.taskSourceId || null]
  );
  return result;
});

ipcMain.handle('get-project', async (event, id: number) => {
  const db = getDatabase();
  return await db.get('SELECT * FROM Project WHERE Id = ?', [id]);
});

ipcMain.handle('update-project', async (event, project: { id: number; title: string; prefix: string; startDate?: string; dueDate?: string; ownerId?: number; taskSourceId?: number }) => {
  const db = getDatabase();
  const result = await db.run(
    'UPDATE Project SET Title = ?, Prefix = ?, StartDate = ?, DueDate = ?, OwnerId = ?, TaskSourceId = ? WHERE Id = ?',
    [project.title, project.prefix, project.startDate || null, project.dueDate || null, project.ownerId || null, project.taskSourceId || null, project.id]
  );
  return result;
});

// Person IPC Handlers
ipcMain.handle('get-people', async () => {
  const db = getDatabase();
  return await db.all('SELECT * FROM Person ORDER BY Name ASC');
});

ipcMain.handle('create-person', async (event, person: { name: string; email: string; color?: string }) => {
  const db = getDatabase();
  return await db.run(
    'INSERT INTO Person (Name, Email, Color) VALUES (?, ?, ?)',
    [person.name, person.email, person.color || null]
  );
});

ipcMain.handle('update-person', async (event, person: { id: number; name: string; email: string; color?: string }) => {
  const db = getDatabase();
  return await db.run(
    'UPDATE Person SET Name = ?, Email = ?, Color = ? WHERE Id = ?',
    [person.name, person.email, person.color || null, person.id]
  );
});

ipcMain.handle('delete-person', async (event, id: number) => {
  const db = getDatabase();
  return await db.run('DELETE FROM Person WHERE Id = ?', [id]);
});

// Status IPC Handlers
ipcMain.handle('get-statuses', async () => {
  const db = getDatabase();
  return await db.all('SELECT * FROM Status ORDER BY Id ASC');
});

ipcMain.handle('create-status', async (event, status: { label: string; isNew: boolean; isComplete: boolean }) => {
  const db = getDatabase();
  return await db.run(
    'INSERT INTO Status (Label, IsNew, IsComplete) VALUES (?, ?, ?)',
    [status.label, status.isNew ? 1 : 0, status.isComplete ? 1 : 0]
  );
});

ipcMain.handle('update-status', async (event, status: { id: number; label: string; isNew: boolean; isComplete: boolean }) => {
  const db = getDatabase();
  return await db.run(
    'UPDATE Status SET Label = ?, IsNew = ?, IsComplete = ? WHERE Id = ?',
    [status.label, status.isNew ? 1 : 0, status.isComplete ? 1 : 0, status.id]
  );
});

ipcMain.handle('delete-status', async (event, id: number) => {
  const db = getDatabase();
  return await db.run('DELETE FROM Status WHERE Id = ?', [id]);
});

// Task IPC Handlers
ipcMain.handle('get-task', async (event, id: number) => {
  const db = getDatabase();
  const task = await db.get(`
    SELECT t.*, p.Name as AssigneeName, s.Label as StatusLabel, s.IsComplete, pt.Title as ParentTitle
    FROM Task t
    LEFT JOIN Person p ON t.AssigneeId = p.Id
    LEFT JOIN Status s ON t.StatusId = s.Id
    LEFT JOIN Task pt ON t.ParentId = pt.Id
    WHERE t.Id = ?
  `, [id]);

  if (!task) return null;

  const prerequisites = await db.all(`
    SELECT tp.*, t.Title as PrerequisiteTaskTitle, s.IsComplete as PrerequisiteIsComplete
    FROM TaskPrerequisite tp
    JOIN Task t ON tp.PrerequisiteTaskId = t.Id
    LEFT JOIN Status s ON t.StatusId = s.Id
    WHERE tp.TaskId = ?
  `, [id]);

  const dependedOnBy = await db.all(`
    SELECT tp.*, t.Title as DependentTaskTitle, s.IsComplete as DependentIsComplete
    FROM TaskPrerequisite tp
    JOIN Task t ON tp.TaskId = t.Id
    LEFT JOIN Status s ON t.StatusId = s.Id
    WHERE tp.PrerequisiteTaskId = ?
  `, [id]);

  return { task, prerequisites, dependedOnBy };
});

ipcMain.handle('get-project-tasks', async (event, projectId: number) => {
  const db = getDatabase();
  const tasks = await db.all(`
    SELECT t.*, p.Name as AssigneeName, s.Label as StatusLabel, s.IsComplete, pt.Title as ParentTitle
    FROM Task t
    LEFT JOIN Person p ON t.AssigneeId = p.Id
    LEFT JOIN Status s ON t.StatusId = s.Id
    LEFT JOIN Task pt ON t.ParentId = pt.Id
    WHERE t.ProjectId = ?
    ORDER BY t.SortOrder ASC, t.DisplayId ASC
  `, [projectId]);

  // Get prerequisites where either the task or the prerequisite is in the project
  // This ensures we have both what tasks in the project depend on, 
  // and what depends on tasks in the project.
  const prerequisites = await db.all(`
    SELECT tp.*, 
           pt.Title as PrerequisiteTaskTitle, 
           ps.IsComplete as PrerequisiteIsComplete,
           dt.Title as DependentTaskTitle,
           ds.IsComplete as DependentIsComplete
    FROM TaskPrerequisite tp
    JOIN Task pt ON tp.PrerequisiteTaskId = pt.Id
    JOIN Task dt ON tp.TaskId = dt.Id
    LEFT JOIN Status ps ON pt.StatusId = ps.Id
    LEFT JOIN Status ds ON dt.StatusId = ds.Id
    WHERE pt.ProjectId = ? OR dt.ProjectId = ?
  `, [projectId, projectId]);

  return { tasks, prerequisites };
});

ipcMain.handle('create-task', async (event, task: { 
  displayId: number;
  title: string; 
  projectId: number; 
  sortOrder: number;
  description?: string; 
  assigneeId?: number; 
  statusId?: number;
  parentId?: number;
  remoteTaskId?: number;
}) => {
  const db = getDatabase();
  return await db.run(
    'INSERT INTO Task (DisplayId, Title, ProjectId, SortOrder, Description, AssigneeId, StatusId, ParentId, RemoteTaskId) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)',
    [
      task.displayId,
      task.title,
      task.projectId,
      task.sortOrder,
      task.description || null,
      task.assigneeId || null,
      task.statusId || null,
      task.parentId || null,
      task.remoteTaskId || null
    ]
  );
  });

  ipcMain.handle('update-task', async (event, task: {
  id: number;
  title: string;
  description?: string;
  assigneeId?: number;
  statusId?: number;
  parentId?: number;
  remoteTaskId?: number;
  }) => {
  const db = getDatabase();
  return await db.run(
    'UPDATE Task SET Title = ?, Description = ?, AssigneeId = ?, StatusId = ?, ParentId = ?, RemoteTaskId = ? WHERE Id = ?',
    [
      task.title,
      task.description || null,
      task.assigneeId || null,
      task.statusId || null,
      task.parentId || null,
      task.remoteTaskId || null,
      task.id
    ]
  );
  });
ipcMain.handle('add-prerequisite', async (event, { taskId, prerequisiteTaskId, type }) => {
  const db = getDatabase();
  return await db.run(
    'INSERT INTO TaskPrerequisite (TaskId, PrerequisiteTaskId, Type) VALUES (?, ?, ?)',
    [taskId, prerequisiteTaskId, type]
  );
});

ipcMain.handle('update-prerequisite', async (event, { taskId, prerequisiteTaskId, type }) => {
  const db = getDatabase();
  return await db.run(
    'UPDATE TaskPrerequisite SET Type = ? WHERE TaskId = ? AND PrerequisiteTaskId = ?',
    [type, taskId, prerequisiteTaskId]
  );
});

ipcMain.handle('delete-prerequisite', async (event, { taskId, prerequisiteTaskId }) => {
  const db = getDatabase();
  return await db.run(
    'DELETE FROM TaskPrerequisite WHERE TaskId = ? AND PrerequisiteTaskId = ?',
    [taskId, prerequisiteTaskId]
  );
});

ipcMain.handle('update-task-orders', async (event, updates: { id: number; sortOrder: number }[]) => {
  const db = getDatabase();
  // Using a loop here; for better performance in larger sets, consider a transaction or bulk update.
  for (const update of updates) {
    await db.run('UPDATE Task SET SortOrder = ? WHERE Id = ?', [update.sortOrder, update.id]);
  }
});

// Azure DevOps Integration - Task Import
type DbTaskSource = {
  Id: number;
  Name: string;
  Type: string;
  Config: string; // JSON string
};

type DbPerson = {
  Id: number;
  Name: string;
  Email: string;
  Color: string;
};

type DbStatus = {
  Id: number;
  Label: string;
  IsNew: 0 | 1;
  IsComplete: 0 | 1;
};

type DbStatusMap = {
  Id: number;
  TaskSourceId: number;
  StatusId: number;
  SourceName: string;
};

ipcMain.handle('import-tasks-from-source', async (event, projectId: number, taskSourceId: number, workItemIdsString: string) => {
  const db = getDatabase();
  let connection: azdev.WebApi | undefined;

  try {
    // 1. Fetch TaskSource details
    const taskSource: DbTaskSource = await db.get('SELECT * FROM TaskSource WHERE Id = ?', [taskSourceId]);
    if (!taskSource) {
      throw new Error(`TaskSource with ID ${taskSourceId} not found.`);
    }

    const config = JSON.parse(taskSource.Config);
    const { organizationUrl, pat } = config;

    if (!organizationUrl || !pat) {
      throw new Error('TaskSource configuration missing organizationUrl or pat.');
    }

    // 2. Connect to Azure DevOps
    const authHandler = azdev.getPersonalAccessTokenHandler(pat);
    connection = new azdev.WebApi(organizationUrl, authHandler);
    const witApi = await connection.getWorkItemTrackingApi();

    // 3. Parse work item IDs
    const workItemIds = workItemIdsString.split(',').map(id => parseInt(id.trim(), 10)).filter(id => !isNaN(id));
    if (workItemIds.length === 0) {
      throw new Error('No valid work item IDs provided.');
    }

    // 4. Fetch work items from Azure DevOps
    const azDevWorkItems = await witApi.getWorkItems(workItemIds, undefined, undefined, WITInterfaces.WorkItemExpand.Relations);
    // 5. Fetch StatusMap entries and local People
    const statusMaps: DbStatusMap[] = await db.all('SELECT * FROM StatusMap WHERE TaskSourceId = ?', [taskSourceId]);
    const people: DbPerson[] = await db.all('SELECT * FROM Person');
    const statuses: DbStatus[] = await db.all('SELECT * FROM Status');

    const defaultNewStatus = statuses.find(s => s.IsNew === 1) || statuses[0];
    if (!defaultNewStatus) {
      throw new Error('No default "New" status found in the database.');
    }

    // 6. Fetch existing tasks in the project to determine next DisplayId and SortOrder
    const existingTasks: { DisplayId: number; SortOrder: number }[] = await db.all(
      'SELECT DisplayId, SortOrder FROM Task WHERE ProjectId = ?',
      [projectId]
    );
    let maxDisplayId = existingTasks.length > 0 ? Math.max(...existingTasks.map(t => t.DisplayId)) : 0;
    let maxSortOrder = existingTasks.length > 0 ? Math.max(...existingTasks.map(t => t.SortOrder)) : 0;

    await db.run('BEGIN TRANSACTION');
    try {
      for (const wi of azDevWorkItems) {
        if (!wi.id || !wi.fields) continue;

        const title = wi.fields['System.Title'];
        const description = wi.fields['System.Description'];
        const azDevStatus = wi.fields['System.State'];
        const assignedTo = wi.fields['System.AssignedTo']; // object with displayName, uniqueName, etc.
        const remoteTaskId = wi.id;

        // Map status
        let statusId: number | null = defaultNewStatus.Id;
        const mappedStatus = statusMaps.find(sm => sm.SourceName.toLowerCase() === azDevStatus.toLowerCase());
        if (mappedStatus) {
          statusId = mappedStatus.StatusId;
        } else {
          console.warn(`No status map found for Azure DevOps status "${azDevStatus}". Using default new status.`);
        }

        // Map assignee
        let assigneeId: number | null = null;
        if (assignedTo && (assignedTo.displayName || assignedTo.uniqueName)) {
          const assigneeName = assignedTo.displayName;
          const assigneeEmail = assignedTo.uniqueName; // Often email format

          const matchedPerson = people.find(p =>
            p.Name.toLowerCase() === assigneeName.toLowerCase() ||
            (p.Email && assigneeEmail && p.Email.toLowerCase() === assigneeEmail.toLowerCase())
          );

          if (matchedPerson) {
            assigneeId = matchedPerson.Id;
          } else {
            console.warn(`No local person found for assignee "${assigneeName || assigneeEmail}". Task will be unassigned.`);
          }
        }

        maxDisplayId++;
        maxSortOrder += 10;

        await db.run(
          'INSERT INTO Task (DisplayId, Title, ProjectId, SortOrder, Description, AssigneeId, StatusId, RemoteTaskId) VALUES (?, ?, ?, ?, ?, ?, ?, ?)',
          [
            maxDisplayId,
            title,
            projectId,
            maxSortOrder,
            description || null,
            assigneeId,
            statusId,
            remoteTaskId
          ]
        );
      }
      await db.run('COMMIT');
      console.log(`Successfully imported ${azDevWorkItems.length} tasks.`);
    } catch (innerError) {
      await db.run('ROLLBACK');
      console.error('Error during task import transaction:', innerError);
      throw innerError;
    }
  } catch (error) {
    console.error('Failed to import tasks from Azure DevOps:', error);
    throw error;
  } finally {
    if (connection) {
      // connection.disconnect(); // azure-devops-node-api does not have a disconnect method
    }
  }
});


ipcMain.handle('get-task-sources', async () => {
  const db = getDatabase();
  return await db.all('SELECT * FROM TaskSource ORDER BY Id ASC');
});

ipcMain.handle('create-task-source', async (event, source: { name: string; type: string; config: string }) => {
  const db = getDatabase();
  return await db.run(
    'INSERT INTO TaskSource (Name, Type, Config) VALUES (?, ?, ?)',
    [source.name, source.type, source.config]
  );
});

ipcMain.handle('update-task-source', async (event, source: { id: number; name: string; type: string; config: string }) => {
  const db = getDatabase();
  return await db.run(
    'UPDATE TaskSource SET Name = ?, Type = ?, Config = ? WHERE Id = ?',
    [source.name, source.type, source.config, source.id]
  );
});

ipcMain.handle('delete-task-source', async (event, id: number) => {
  const db = getDatabase();
  return await db.run('DELETE FROM TaskSource WHERE Id = ?', [id]);
});

// StatusMap IPC Handlers
ipcMain.handle('get-status-maps', async (event, taskSourceId: number) => {
  const db = getDatabase();
  return await db.all('SELECT * FROM StatusMap WHERE TaskSourceId = ?', [taskSourceId]);
});

ipcMain.handle('update-status-maps', async (event, taskSourceId: number, maps: { statusId: number; sourceName: string }[]) => {
  const db = getDatabase();
  await db.run('BEGIN TRANSACTION');
  try {
    // Delete existing mappings for this TaskSource
    await db.run('DELETE FROM StatusMap WHERE TaskSourceId = ?', [taskSourceId]);

    // Insert new mappings
    for (const map of maps) {
      await db.run(
        'INSERT INTO StatusMap (TaskSourceId, StatusId, SourceName) VALUES (?, ?, ?)',
        [taskSourceId, map.statusId, map.sourceName]
      );
    }
    await db.run('COMMIT');
  } catch (error) {
    await db.run('ROLLBACK');
    console.error('Error updating status maps:', error);
    throw error;
  }
});

ipcMain.handle('open-external', async (event, url: string) => {
  return await shell.openExternal(url);
});

ipcMain.handle('find-task-by-display-id', async (event, { input, currentProjectId }) => {
  const db = getDatabase();
  const parts = input.split('-');
  
  if (parts.length === 2) {
    const [prefix, displayId] = parts;
    return await db.get(`
      SELECT t.Id 
      FROM Task t 
      JOIN Project p ON t.ProjectId = p.Id 
      WHERE p.Prefix = ? AND t.DisplayId = ?
    `, [prefix.toUpperCase(), Number(displayId)]);
  } else {
    return await db.get(`
      SELECT Id FROM Task WHERE ProjectId = ? AND DisplayId = ?
    `, [currentProjectId, Number(input)]);
  }
});

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', async () => {
  await closeDatabase();
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('will-quit', async () => {
  await closeDatabase();
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});
